branches:
  only:
    - master
language: go
sudo: false
go:
- 1.5
- tip
cache:
  directories:
  - $HOME/local
before_install:
- ./.travis.build-protoc.sh 3.0.0-beta-2
- go get github.com/golang/lint/golint
install:
- go get github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway
- go get github.com/gengo/grpc-gateway/runtime
- go get github.com/gengo/grpc-gateway/examples
- go get github.com/gengo/grpc-gateway/examples/server
script:
- make realclean && make examples
- if ! go version | grep devel; then test -z "$(git status --porcelain)" || (git status; git diff; exit 1); fi
- env GLOG_logtostderr=1 go test -race -v github.com/gengo/grpc-gateway/...
- golint github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway/...
- golint github.com/gengo/grpc-gateway/runtime/...
- golint github.com/gengo/grpc-gateway/utilities/...
- go vet github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway/...
- go vet github.com/gengo/grpc-gateway/runtime/... || true
- go vet github.com/gengo/grpc-gateway/utilities/...
env:
  global:
  - "PATH=$PATH:$HOME/local/bin"
